baseURL = 'https://brunojesus.pt/'
languageCode = 'en-us'
title = 'Bruno Jesus'
theme = 'typo'
disableKinds = ["taxonomy", "term", "taxonomyTerm"]

#[taxonomies]
#tag = 'tags'

# Google analytics code
#googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "Welcome to my internet corner!"

# Appearance settings
colorPalette = 'catpuccin'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
<p>
  My name is <b>Bruno Jesus</b>, and I am a software developer currently working for <a href="https://commercetools.com" class="text-marker-mauve">Commercetools</a>.
</p>
<p>Feel free to <a class="text-marker-teal" href="/cv.pdf">download my CV</a>, I left some stuff out for the sake of simplicity... and I really wanted it to fit nicely in one A4 page!</p>
<p>
  If you have any suggestions or would like to collaborate, please feel free to <a href="mailto:bruno.fl.jesus@gmail.com" class="text-marker-blue">contact me</a>.
</p>
"""

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/bruno-jesus-0ab943a9/"

[[params.social]]
name = "github"
url = "https://github.com/brunofjesus"

[[params.social]]
name = "cv"
url = "/cv.pdf"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.skill]]
name = "Golang"
emoji = "❤️"
description = "Fell in love with it's ease of use, performance, and did I say it compiles to a single binary?"

[[params.skill]]
name = "Java"
emoji = "👌"
description = "Was part of my day to day life from 2017 to 2022. After that I mainly used it for teaching."

[[params.skill]]
name = "PHP"
emoji = "🤷"
description = "Some systems at my current job use it, that means I have to use it as well."

[[params.skill]]
name = "TypeScript"
emoji = "😐"
description = "Makes JavaScript bearable and gets the job done."

[[params.skill]]
name = "Python"
emoji = "🤓"
description = "I don't really use it much nowadays."

[[params.skill]]
name = "Kubernetes"
emoji = "😇"
description = "I guess I like it because I don't really have to maintain it!"


[[params.experience]]
place = "Commercetools"
title = "Senior Software Engineer"
time = "2022-01 / Present"
description = """
Development of <a href="https://commercetools.com/features/frontend" class="text-marker-mauve">Commercetools Frontend</a>.
<br/>
Spearheaded the transition to multi-tenancy with Kubernetes and Telemetry/Observability design and implementation.
"""
[[params.experience]]
place = "Escola Superior de Gestão e Tecnologia de Santarém"
title = "Invited Assistant"
time = "2021-10 / 2024-07"
description = """
Teaching of Relational Databases, Systems Integration and Software Engineering on CTeSP courses.
"""

[[params.experience]]
place = "Mercedes-Benz.io @ Cloudmobility"
title = "Senior Software Engineer"
time = "2021-08 / 2022-02"
description = """
Development of cNS (Cloudmobility Namespaces), a private cloud for Daimler.
"""

[[params.experience]]
place = "Volkswagen Digital Solutions @ MAN Digital Hub"
title = "Software Engineer"
time = "2020-03 / 2021-08"
description = """
Development of a Manufacturing Execution System for MAN Truck & Bus.
"""

[[params.experience]]
place = "Alter Solutions @ AXA Belgium"
title = "Software Engineer"
time = "2019-06 / 2020-03"
description = """
Development of <a href="https://www.axa.be/myaxaaccidentatwork" class="text-marker-teal">MyAXA Accident@Work</a>.
"""

[[params.experience]]
place = "Maxdata"
title = "Software Engineer"
time = "2017/06 - 2019/06"
description = """
Development of <a href="https://www.maxdata.pt/" class="text-marker-blue">Clinidata</a> healthcare software.
"""

[[params.experience]]
place = "Redislogar"
title = "Freelancer Developer"
time = "2016/02 - 2016/04"
description = """
Configuration of a custom Linux distribution, system security and development of an update system for their HomePaq machines.
"""

[[params.experience]]
place = "ConnectedTI"
title = "Intern"
time = "2014-06 / 2014-08"
description = """
Internship for my specialization Course, development of a CRM for a Call Center.
"""

[[params.experience]]
place = "Wolfd"
title = "Junior Developer"
time = "2012-06 / 2013-09"
description = """
Most of my time in this company was occupied by the development of Rediskey which turned out to be my first \"big\" project.
"""

# Syntax highligth on code blocks
[markup]
[markup.highlight]
noClasses = false

# Giscus comments
#[params.giscus]
#enable = false
#repo = "user/repo"
#repoid = "repoId"
#category = "General"
#categoryid = "categoryId"
#mapping = "pathname"
#theme = "preferred_color_scheme"
