baseURL = 'https://brunojesus.pt/'
languageCode = 'en-us'
title = 'Bruno Jesus'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
#googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "Welcome to my internet corner!"

# Appearance settings
colorPalette = 'catpuccin'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
<p>
  My name is <b>Bruno Jesus</b>, and I am a software developer currently working for <a href="https://commercetools.com" class="text-marker-mauve">Commercetools</a>.
</p>
<p>
  I hope some of my <a href="/posts" class="text-marker-peach">posts</a> have been useful to you.
  If you have any suggestions or would like to collaborate, please feel free to <a href="mailto:bruno.fl.jesus@gmail.com" class="text-marker-blue">contact me</a>.
</p>
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/bruno-jesus-0ab943a9/"

[[params.social]]
name = "github"
url = "https://github.com/brunofjesus"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.skill]]
name = "Golang"
description = "Best language ever! Simple and efficient!"

[[params.skill]]
name = "Java"
description = "Was part of my day to day life from 2017 to 2022."

[[params.skill]]
name = "TypeScript"
description = "I'd rather not use it, but it's still better than plain old Javascript."

[[params.skill]]
name = "PHP"
description = "Using it at Commercetools. Gets the job done."

[[params.skill]]
name = "Python"
description = "Used it a lot in the past, but I now use it only occasionally."

[[params.skill]]
name = "Kubernetes"
description = "Working with since I started at Cloudmobility and now on Commercetools as well."


[[params.experience]]
place = "Commercetools"
title = "Software Developer"
time = "2022-01 / Present"
description = """
Development of <a href="https://commercetools.com/features/frontend" class="text-marker-mauve">Commercetools Frontend</a>
"""
[[params.experience]]
place = "Escola Superior de Gestão e Tecnologia de Santarém"
title = "Invited Assistant"
time = "2021-10 / 2024-07"
description = """
Teaching of Relational Databases, Systems Integration and Software Engineering on CTeSP courses.
"""

[[params.experience]]
place = "Mercedes-Benz.io @ Cloudmobility"
title = "Software Engineer"
time = "2021-08 / 2022-02"
description = """
Development of cNS (Cloudmobility Namespaces), a private cloud for Daimler.
"""

[[params.experience]]
place = "Volkswagen Digital Solutions @ MAN Digital Hub"
title = "Software Engineer"
time = "2020-03 / 2021-08"
description = """
Development of a Manufacturing Execution System for MAN Truck & Bus.
"""

[[params.experience]]
place = "Alter Solutions @ AXA Belgium"
title = "Software Developer"
time = "2019-06 / 2020-03"
description = """
Development of <a href="https://www.axa.be/myaxaaccidentatwork" class="text-marker-teal">MyAXA Accident@Work</a>.
"""

[[params.experience]]
place = "Maxdata"
title = "Software Developer"
time = "2017/06 - 2019/06"
description = """
Development of <a href="https://www.maxdata.pt/" class="text-marker-blue">Clinidata</a> healthcare software.
"""

[[params.experience]]
place = "Redislogar"
title = "Freelancer Developer"
time = "2016/02 - 2016/04"
description = """
Configuration of a custom Linux distribution, system security and development of an update system for their HomePaq machines.
"""

[[params.experience]]
place = "ConnectedTI"
title = "Intern"
time = "2014-06 / 2014-08"
description = """
Internship for my specialization Course, development of a CRM for a Call Center.
"""

[[params.experience]]
place = "Wolfd"
title = "Developer"
time = "2012-06 / 2013-09"
description = """
Most of my time in this company was occupied by the development of Rediskey which turned out to be my first \"big\" project.
"""

# Syntax highligth on code blocks
[markup]
[markup.highlight]
noClasses = false

# Giscus comments
#[params.giscus]
#enable = false
#repo = "user/repo"
#repoid = "repoId"
#category = "General"
#categoryid = "categoryId"
#mapping = "pathname"
#theme = "preferred_color_scheme"
